### ISSUE TITLE
Is there a free camera option?

### ISSUE THREAD

**Issue by Zigaru** [Kiloutre/TKMovesets#152]
Hi, Kilo and friends. Just wondering, is an option for the free camera just like in the previous app available? Sorry in advance just in case I missed the option to enable the feature.

**Comment by Kiloutre** [comment]
There isn't, TKMovesets is only related to moveset editing/playing (at least for now) and aims to addd all kind features only related to that, . If you need to move the camera around then the old tool is still functional for that.
I'm also interested in moving the camera around for T8, so eventually i'll make something for that, but we're not there yet.
