### ISSUE TITLE
Tekken 6 PPSSPP extraction problem

### ISSUE THREAD

**Issue by dawnofviolence** [Kiloutre/TKMovesets#165]
Hello - Every game I have tried with this tool has been detected properly and can extract just fine, except for the PSP version of T6. I have the right version (ULUS10466) and have tried on PPSSPP 1.15, 1.15.4, & a nightly build of 1.15.4, to no avail.
![image](https://github.com/Kiloutre/TKMovesets/assets/36431712/e71c45e5-5641-41e5-b1e3-2cea62f67b4f)

**Comment by Kiloutre** [comment]
The interface doesn't indicate this yet but the PPSSPP version requires obtaining the base address of the game once it is running, providing it in the game_addresses.ini file and restarting the software
Also the PSP version does not contain move names iirc, as opposed to other Tekken 6 versions. You should avoid using it for that reason.

**Comment by globalsdotcpk** [comment]
I see, thank you for the response
